import React from 'react';

import './modules.css'

function Carbon() {
    return ( 
        <div className="carbon-content">
            <h2>Carbon</h2>
            <p>In FedERA CodeCarbon package is used to estimate the carbon emissions generated by clients during training. CodeCarbon is a Python package that provides an estimation of the carbon emissions associated with software code.</p>
        </div>
    )
};

export default Carbon;